### PR TITLE
adding closing reflective exercise

### PR DESCRIPTION
**Pull request by ChristinaLK**
as discussed by @sstevens2 and I after the workshop today. 😁

### CODE REVIEW

**Review by sstevens2 — APPROVED** [review]
Looks good!  I'll go ahead and merge!

**Comment by sstevens2** [comment]
Oops better wait for the other review from @aturner-epcc

**Comment by ChristinaLK** [comment]
LOL, that was just me increasing my options for review, but I would like @aturner-epcc 's feedback if he has time!

**Review by aturner-epcc — APPROVED** [review]
Looks good to me - it is always good to finish on a reflection exercise!

**Comment by ChristinaLK** [comment]
Thank you both. :grin:

**Pull request merged**
