### PR TITLE
Port to Workbench format

### LINKED ISSUE #217: Convert to Workbench format
There is a tool do this, but I haven't tried it myself: https://github.com/carpentries/lesson-transition#readme

### PR DESCRIPTION
**Pull request by multimeric**
Closes #217. 

You can find the rendered HTML here: https://wehi-researchcomputing.github.io/docker-introduction/.

Feedback is welcome.

### CODE REVIEW

**Comment by multimeric** [comment]
Something I'm not sure about.  The current material has objectives in the introduction page: https://github.com/carpentries-incubator/docker-introduction/blob/15b3b4ff4f31b542d6b522262f3561ce69cb0801/index.md#L8-L20

No workbench lessons seem to do this, and indeed the workbench won't even display objectives in the intro. Not sure if I should delete these entirely?

**Comment by multimeric** [comment]
I've also manually now checked all the output episodes, and I'm happy with everything. Nothing seems to have been missed.

**Comment by aturner-epcc** [comment]
> Something I'm not sure about. The current material has objectives in the introduction page:
> 
> https://github.com/carpentries-incubator/docker-introduction/blob/15b3b4ff4f31b542d6b522262f3561ce69cb0801/index.md#L8-L20
> 
> No workbench lessons seem to do this, and indeed the workbench won't even display objectives in the intro. Not sure if I should delete these entirely?

I think they can just be moved into the main text that appears at the top of the Summary and Setup page. It is important for learners to have an overview of what they will gain from the lesson so I would not want to lose them entirely.

**Comment by aturner-epcc** [comment]
Thanks for all the work on this, I will have a look through and add any comments in my review.

**Comment by multimeric** [comment]
> I think they can just be moved into the main text that appears at the top of the Summary and Setup page. It is important for learners to have an overview of what they will gain from the lesson so I would not want to lose them entirely.

Currently I have it in a `callout` in this location: https://wehi-researchcomputing.github.io/docker-introduction/#after-completing-this-session-you-should. Let me know what you think.

**Comment by aturner-epcc** [comment]
That looks perfect! I'll go through the rest of the PR over the next day or two.

**Comment by multimeric** [comment]
If you could run a github pages build too, that would be great.

**Comment by aturner-epcc** [comment]
I do not have permission to remove the gh-pages branch from the repo (it's existence is stopping the build from progressing as it pushes to this orphan branch). I have asked the repo admin (@sstevens2 ) to do this. If I don't not get a response soon, I will configure the build and publish to use another branch name.

**Comment by dme26** [comment]
Sorry there's a blocker for your work. Just double-checking that the default branch should become main, and if so I can effect changing the default and deleting gh-pages if sstevens2 isn't available.

**Comment by aturner-epcc** [comment]
Thanks @dme26 . `main` is good for the default branch name

**Comment by dme26** [comment]
I've changed the default branch to `main` and have renamed `gh-pages` to `previous-gh-pages`. Just let me know if this doesn't unblock your progress. (Also, apologies @sstevens2 if I just invoked any particular forms of repository chaos in so doing.)

**Comment by aturner-epcc** [comment]
Thanks @dme26. @multimeric Deployed pages has now updated to workbench format so I think this is all working now.

**Comment by sstevens2** [comment]
Hi all!  Thanks so much for all your work on this! Sorry I missed it in my notifications.  So excited to see this moved to the workbench!

**Pull request merged**
